In [1]:
import numpy as np
import pandas as pd

In [2]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})

In [3]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [4]:
def square(x):
  return x**2

In [7]:
df1['B'] = df1['B'].apply(square)
df1

   A        B    C
0  1    10000  100
1  2   160000  200
2  3   810000  300
3  4  2560000  400
4  5  6250000  500

In [8]:
df1['D'] = df1['B'].apply(lambda x : x**3 )
df1

   A        B    C                      D
0  1    10000  100          1000000000000
1  2   160000  200       4096000000000000
2  3   810000  300     531441000000000000
3  4  2560000  400   16777216000000000000
4  5  6250000  500  244140625000000000000