In [10]:
import pandas as pd
import numpy as np

In [2]:
data = [10, 20, 30, 40]
data

[10, 20, 30, 40]

In [4]:
series = pd.Series(data)
series

0    10
1    20
2    30
3    40
dtype: int64

In [5]:
custom_series = pd.Series(data , index = ['a','b','c','d'])
custom_series

a    10
b    20
c    30
d    40
dtype: int64

In [8]:
data2 = {
    "a1": 10,
    "b1": 20,
    "c1": 30
}

In [9]:
series2 = pd.Series(data2)
series2

a1    10
b1    20
c1    30
dtype: int64

In [11]:
arr = np.arange(1,5)
arr

array([1, 2, 3, 4])

In [12]:
series3 = pd.Series(arr)
series3

0    1
1    2
2    3
3    4
dtype: int64

In [13]:
index = ['w','x','y','z']

In [15]:
series4 = pd.Series(arr,index = index )
series4

w    1
x    2
y    3
z    4
dtype: int64